	<!-- jquery mask -->
	<?php echo $this->headScript()
		 		    ->prependFile($this->basePath() . '/js/jquery.mask.js');
	?>

	</div>
	</div>
		<!-- Content -->
			<div id="content-wrapper">
				<div id="content">
					<div class="container">
						<div class="row">
							<div class="9u">
								
								<!-- Conteúdo Principal -->
									<section>
										<header>
											<h2>Cadastro</h2>
											<h3>Formulário de cadastro para reservas e gerenciamento das suítes</h3>
										</header>

									<form method="post" action="" id="form-cadastro">
										<div class="row">
											<div class="6u">
												<input type="text" id="cad-nome" class="form-input-text inp-nome" placeholder="Nome">
											</div>
											<div class="3u">
												<select name="cad-sexo" id="cad-sexo" class="form-input-text inp-sexo">
													<option value="">Sexo</option>
													<option value="m">Masculino</option>
													<option value="f">Feminino</option>
												</select>
											</div>
											<div class="3u">
												<input type="text" id="cad-data-nasc" class="form-input-text inp-data-nasc" placeholder="Data de Nascimento">
											</div>
										</div>
										
										<div class="row">
											<div class="6u">
												<input type="text" id="cad-cpf" class="form-input-text inp-cpf" placeholder="CPF">
											</div>										
											<div class="6u">
												<input type="text" id="cad-email" class="form-input-text inp-email" placeholder="Email">
											</div>
										</div>

										<div class="row">
											<div class="6u">
												<input type="text" id="cad-telefone" class="form-input-text inp-telefone" placeholder="Telefone">
											</div>
											<div class="6u">
												<input type="text" id="cad-celular" class="form-input-text inp-celular" placeholder="Celular">
											</div>
										</div>
										
										<div class="row">
											<div class="6u">
												<input type="text" id="cad-cep" class="form-input-text inp-cep" placeholder="CEP">
											</div>
											<div class="6u">
												<input type="text" id="cad-end" class="form-input-text inp-end" placeholder="Endereço">
											</div>
										</div>

										<div class="row">
											<div class="6u">
												<input type="text" id="cad-num" class="form-input-text inp-numero" placeholder="Número">
											</div>
											<div class="6u">
												<input type="text" id="cad-Bairro" class="form-input-text inp-bairro" placeholder="Bairro">
											</div>
										</div>
										
										<div class="row">
											<div class="6u">
												<input type="text" id="cad-cidade" class="form-input-text inp-cidade" placeholder="Cidade">
											</div>
											<div class="6u">
												<input type="text" id="cad-estado" class="form-input-text inp-estado" placeholder="Estado">
											</div>
										</div>

										<h3>Formulário para usuário</h3>

										<div class="row">
											<div class="6u">
												<input type="text" id="cad-user" class="form-input-text inp-user" placeholder="Usuário">
											</div>

											<div class="3u">
												<input type="text" id="cad-senha" class="form-input-text inp-senha" placeholder="Senha">
											</div>

											<div class="3u">
												<input type="text" id="cad-confirm-senha" class="form-input-text inp-confirm-senha" placeholder="Confirmar Senha">
											</div>
										</div>

										<div class="row">
											<div class="14u" style="float:right;">
												<input type="button" id="cad-enviar" class="button-enviar" value="Enviar">
											</div>
										</div>
									</form>
									
									</section>
							
							</div>
							<div class="3u">
								
								<!-- Sidebar -->
									<section>
										<header>
											<h2>Veja Mais:</h2>
										</header>
										<ul class="link-list">
											<li><a href="#">Reservas</a></li>
											<li><a href="#">Suítes</a></li>
											<li><a href="#">Serviços</a></li>
											<li><a href="#">Contato</a></li>
										</ul>
									</section>

							</div>
						</div>
					</div>
				</div>
			</div>
<script>
 	$("#cad-data-nasc").mask("99/99/9999");
	$("#cad-cpf").mask("999.999.999-99"); 
	$("#cad-telefone").mask("(99) 9999-9999");
	$("#cad-celular").mask("(99) 99999-9999");
	$("#cad-cep").mask("99999-999"); 

    function validateEmail(sEmail) {
        var filter = /^([\w-\.]+)@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.)|(([\w-]+\.)+))([a-zA-Z]{2,4}|[0-9]{1,3})(\]?)$/;
        if (filter.test(sEmail)) {
            return true;
        }
        else {
            return false;
        }
    }

    function validateCPF(cpf) {
         
            cpf = cpf.replace(/[^\d]+/g,'');
         
            if(cpf == '') return false;
         
            // Elimina CPFs invalidos conhecidos
            if (cpf.length != 11 || 
                cpf == "00000000000" || 
                cpf == "11111111111" || 
                cpf == "22222222222" || 
                cpf == "33333333333" || 
                cpf == "44444444444" || 
                cpf == "55555555555" || 
                cpf == "66666666666" || 
                cpf == "77777777777" || 
                cpf == "88888888888" || 
                cpf == "99999999999")
                return false;
             
            // Valida 1o digito
            add = 0;
            for (i=0; i < 9; i ++)
                add += parseInt(cpf.charAt(i)) * (10 - i);
            rev = 11 - (add % 11);
            if (rev == 10 || rev == 11)
                rev = 0;
            if (rev != parseInt(cpf.charAt(9)))
                return false;
             
            // Valida 2o digito
            add = 0;
            for (i = 0; i < 10; i ++)
                add += parseInt(cpf.charAt(i)) * (11 - i);
            rev = 11 - (add % 11);
            if (rev == 10 || rev == 11)
                rev = 0;
            if (rev != parseInt(cpf.charAt(10)))
                return false;
                 
            return true;
            
        }


    $('#cad-enviar').click(function() { 
        if($('#cad-nome').val() == '') {
            $('.erro').append('<div>Nome é requirido!</div>');
            $('#cad-nome').focus();
            return false;
        }

        if($('#cad-sexo').val() == '') {
            $('.erro').append('<div>Sexo é requirido!</div>');
            $('#cad-sexo').focus();
            return false;
        }

        if($('#cad-data-nasc').val() == '') {
            $('.erro').append('<div>Data de nascimento é requirido!</div>');
            $('#cad-data-nasc').focus();
            return false;
        }

        if($('#cad-cpf').val() == '') {
            $('#mensagem').append('<div>CPF é requirido!</div>');
            $('#cad-cpf').focus();
            return false;
        }

        if(!validateCPF($('#cad-cpf').val())) {
            $('#mensagem').append('<div>CPF é inválido!</div>');
            $('#cad-cpf').focus();
            return false;
        }

        if($('#cad-email').val() == '') {
            $('.erro').append('<div>Email é requirido!</div>');
            $('#email').focus();
            return false;
        }

        if(!validateEmail($('#cad-email').val())) {
            $('.erro').append('<div>Email é inválido!</div>');
            $('#cad-email').focus();
            return false;
        }

        $.ajax({
            url: "/cadastro/salvar",
            type: "POST",
            data: ({
                nome: $('#cad-nome').val(),
                email: $('#email').val(),
                assunto: $('#assunto').val(),
                id_empreendimento : $('#form-informacoes #id_empreendimento').val()
            }),
            success: function(msg){ 
                $("#form-informacoes").trigger('reset'); 
                $('.erro').append('<div style="color: #27ae60;">Enviado com Sucesso!</div>');
                setTimeout(function() {
                      $('.erro').empty();
                      fecharInformacoes();
                }, 5000);
            }
        });       
    });

</script>
