<?php echo $this->doctype(); ?>

<html lang="pt-br">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('ZF2 '. $this->translate('Skeleton Application'))->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                        ->prependStylesheet($this->basePath() . '/css/style.css')
                        ->prependStylesheet($this->basePath() . '/css/forms.css')
                        ->prependStylesheet($this->basePath() . '/css/skel-noscript.css')
                        ->prependStylesheet($this->basePath() . '/css/style-desktop.css') ?>

        <!-- Scripts -->
        <?php echo $this->headScript()
            ->prependFile($this->basePath() . '/js/config.js')
            ->prependFile($this->basePath() . '/js/jquery-ajaxLink.js')
            ->prependFile($this->basePath() . '/js/bootstrap.min.js')
            ->prependFile($this->basePath() . '/js/jquery.js')
            ->prependFile($this->basePath() . '/js/skel-panels.min.js')
            ->prependFile($this->basePath() . '/js/skel.min.js')
            ->prependFile($this->basePath() . '/js/respond.min.js', 'text/javascript', array('conditional' => 'lt IE 9',))
            ->prependFile($this->basePath() . '/js/html5shiv.js',   'text/javascript', array('conditional' => 'lt IE 9',))
        ; ?>    
    <!--[if lte IE 9]><link rel="stylesheet" href="/css/ie9.css" /><![endif]-->
        
    </head>
    <body>
        
        <!-- Header -->
            <div id="header-wrapper">
                <header id="header" class="container" style="position:relative;">
                    <div class="row">
                        <div class="12u">
                        
                            <!-- Logo -->
                                <h1><a href="/" id="logo">London Pallace</a></h1>
                            
                            <!-- Nav -->
                                <nav id="nav">
                                    <a href="/">Homepage</a>
                                    <a href="/servicos">Serviços</a>
                                    <a href="/suites">Suítes</a>
                                    <a href="/cadastro">Cadastro</a>
                                    <a href="/login" class="fadeLogin">Login</a>
                                </nav>
                        </div>
                    </div>
                </header>

        <div id="login" style="display:none;">
            <div class="arrow-up"></div>
            <div class="2u login-pop-up">
                <div class="9u" style="padding-top:10%; margin:auto;">
                    <input type="text" id="cad-user" class="form-input-login inp-user" placeholder="Usuário">
                </div>
                <div class="9u" style="margin:auto;">
                    <input type="text" id="cad-senha" class="form-input-login inp-senha" placeholder="Senha">
                </div>
                <div class="9u" style="margin:auto; padding-bottom:10%;">
                    <input type="button" id="login-enviar" class="button-entrar" value="Entrar">
                </div>
            </div>
        </div>
            
        <div class="container">
            <?php echo $this->content; ?>
        </div>

        <!-- Footer -->
            <div id="footer-wrapper">
                <footer id="footer" class="container">
                    <div class="row">
                        <div class="8u">
                        
                            <!-- Links -->
                                <section>
                                    <h2>Links to Important Stuff</h2>
                                    <div>
                                        <div class="row">
                                            <div class="3u">
                                                <ul class="link-list last-child">
                                                    <li><a href="#">Neque amet dapibus</a></li>
                                                    <li><a href="#">Sed mattis quis rutrum</a></li>
                                                    <li><a href="#">Accumsan suspendisse</a></li>
                                                    <li><a href="#">Eu varius vitae magna</a></li>
                                                </ul>
                                            </div>
                                            <div class="3u">
                                                <ul class="link-list last-child">
                                                    <li><a href="#">Neque amet dapibus</a></li>
                                                    <li><a href="#">Sed mattis quis rutrum</a></li>
                                                    <li><a href="#">Accumsan suspendisse</a></li>
                                                    <li><a href="#">Eu varius vitae magna</a></li>
                                                </ul>
                                            </div>
                                            <div class="3u">
                                                <ul class="link-list last-child">
                                                    <li><a href="#">Neque amet dapibus</a></li>
                                                    <li><a href="#">Sed mattis quis rutrum</a></li>
                                                    <li><a href="#">Accumsan suspendisse</a></li>
                                                    <li><a href="#">Eu varius vitae magna</a></li>
                                                </ul>
                                            </div>
                                            <div class="3u">
                                                <ul class="link-list last-child">
                                                    <li><a href="#">Neque amet dapibus</a></li>
                                                    <li><a href="#">Sed mattis quis rutrum</a></li>
                                                    <li><a href="#">Accumsan suspendisse</a></li>
                                                    <li><a href="#">Eu varius vitae magna</a></li>
                                                </ul>
                                            </div>
                                        </div>
                                    </div>
                                </section>

                        </div>
                        <div class="4u">
                            
                            <!-- Blurb -->
                                <section>
                                    <h2>An Informative Text Blurb</h2>
                                    <p>
                                        Duis neque nisi, dapibus sed mattis quis, rutrum accumsan sed. Suspendisse eu 
                                        varius nibh. Suspendisse vitae magna eget odio amet mollis. Duis neque nisi, 
                                        dapibus sed mattis quis, sed rutrum accumsan sed. Suspendisse eu varius nibh 
                                        lorem ipsum amet dolor sit amet lorem ipsum consequat gravida justo mollis.
                                    </p>
                                </section>
                        
                        </div>
                    </div>
                </footer>
            </div>

        <!-- Copyright -->
            <div id="copyright">
                &copy; London Pallace. Todos os direitos reservados. | UNIFIEO | <a href="#">TADS</a>
            </div>
    </body>
</html>
<script>
$(document).ready(function() {
    $('.fadeLogin').ajaxLink(); 
    $('.fadeLogin').click(function() {
        $('#login').fadeToggle();
    });
})
</script>